version: '2'

services:
  travel2car:
    image: travel2car
    container_name: travel2carcontainer
    mem_limit: 512M
    ports:
     - 8080:8080

  travel2flight:
    image: travel2flight
    container_name: travel2flightcontainer
    mem_limit: 512M
    depends_on:
      - travel2car
    entrypoint: ["./dockerize","-wait=tcp://config-server:8080","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8081:8081

  travel2hotel:
    image: travel2hotel
    container_name: travel2hotelcontainer
    mem_limit: 512M
    depends_on:
     - travel2car
     - travel2flight
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8081","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
    - 8082:8082