version: '2'

services:
  travel2car:
    image: travel2car
    container_name: travel2carcontainer
    mem_limit: 512M
    ports:
     - 8080:8080

  travel2flight:
    image: travel2flight
    container_name: travel2flightcontainer
    mem_limit: 512M
    depends_on:
      - travel2car
    ports:
     - 8081:8080
  travel2hotel:
    image: travel2hotel
    container_name: travel2hotelcontainer
    mem_limit: 512M
    depends_on:
     - travel2car
     - travel2flight
    ports:
    - 8082:8080